[2024-04-24T10:15:08.040+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: download_rocket_launches.download_launches manual__2024-04-24T10:15:07.744180+00:00 [queued]>
[2024-04-24T10:15:08.045+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: download_rocket_launches.download_launches manual__2024-04-24T10:15:07.744180+00:00 [queued]>
[2024-04-24T10:15:08.045+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-24T10:15:08.054+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): download_launches> on 2024-04-24 10:15:07.744180+00:00
[2024-04-24T10:15:08.057+0000] {standard_task_runner.py:60} INFO - Started process 1811 to run task
[2024-04-24T10:15:08.059+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'download_rocket_launches', 'download_launches', 'manual__2024-04-24T10:15:07.744180+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/Example_dag.py', '--cfg-path', '/tmp/tmpk5jz75ha']
[2024-04-24T10:15:08.060+0000] {standard_task_runner.py:88} INFO - Job 33: Subtask download_launches
[2024-04-24T10:15:08.083+0000] {task_command.py:423} INFO - Running <TaskInstance: download_rocket_launches.download_launches manual__2024-04-24T10:15:07.744180+00:00 [running]> on host 99514668da53
[2024-04-24T10:15:08.122+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='download_rocket_launches' AIRFLOW_CTX_TASK_ID='download_launches' AIRFLOW_CTX_EXECUTION_DATE='2024-04-24T10:15:07.744180+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-24T10:15:07.744180+00:00'
[2024-04-24T10:15:08.123+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-24T10:15:08.123+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "curl -o /src/launches.json -L 'https://ll.thespacedevs.com/2.0.0/launch/upcoming'"]
[2024-04-24T10:15:08.129+0000] {subprocess.py:86} INFO - Output:
[2024-04-24T10:15:08.133+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2024-04-24T10:15:08.134+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2024-04-24T10:15:09.961+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
[2024-04-24T10:15:11.293+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0Warning: Failed to open the file /src/launches.json: No such file or directory
[2024-04-24T10:15:11.293+0000] {subprocess.py:93} INFO -   5 25873    5  1360    0     0    430      0  0:01:00  0:00:03  0:00:57  4108
[2024-04-24T10:15:11.294+0000] {subprocess.py:93} INFO - curl: (23) Failure writing output to destination
[2024-04-24T10:15:11.294+0000] {subprocess.py:97} INFO - Command exited with return code 23
[2024-04-24T10:15:11.300+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 23.
[2024-04-24T10:15:11.302+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=download_rocket_launches, task_id=download_launches, execution_date=20240424T101507, start_date=20240424T101508, end_date=20240424T101511
[2024-04-24T10:15:11.309+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 33 for task download_launches (Bash command failed. The command returned a non-zero exit code 23.; 1811)
[2024-04-24T10:15:11.320+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-24T10:15:11.331+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
