[2024-04-24T09:48:30.214+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: download_rocket_launches.download_launches manual__2024-04-24T09:48:29.934880+00:00 [queued]>
[2024-04-24T09:48:30.219+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: download_rocket_launches.download_launches manual__2024-04-24T09:48:29.934880+00:00 [queued]>
[2024-04-24T09:48:30.219+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-24T09:48:30.226+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): download_launches> on 2024-04-24 09:48:29.934880+00:00
[2024-04-24T09:48:30.231+0000] {standard_task_runner.py:60} INFO - Started process 566 to run task
[2024-04-24T09:48:30.233+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'download_rocket_launches', 'download_launches', 'manual__2024-04-24T09:48:29.934880+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/Example_dag.py', '--cfg-path', '/tmp/tmpd0sc5rep']
[2024-04-24T09:48:30.234+0000] {standard_task_runner.py:88} INFO - Job 18: Subtask download_launches
[2024-04-24T09:48:30.261+0000] {task_command.py:423} INFO - Running <TaskInstance: download_rocket_launches.download_launches manual__2024-04-24T09:48:29.934880+00:00 [running]> on host 99514668da53
[2024-04-24T09:48:30.337+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='download_rocket_launches' AIRFLOW_CTX_TASK_ID='download_launches' AIRFLOW_CTX_EXECUTION_DATE='2024-04-24T09:48:29.934880+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-24T09:48:29.934880+00:00'
[2024-04-24T09:48:30.338+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-24T09:48:30.339+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "curl -o tmp/launches.json -L 'https://ll.thespacedevs.com/2.0.0/launch/upcoming'"]
[2024-04-24T09:48:30.344+0000] {subprocess.py:86} INFO - Output:
[2024-04-24T09:48:30.349+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2024-04-24T09:48:30.349+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2024-04-24T09:48:36.303+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
[2024-04-24T09:48:36.760+0000] {subprocess.py:93} INFO - Warning: Failed to open the file tmp/launches.json: No such file or directory
[2024-04-24T09:48:36.761+0000] {subprocess.py:93} INFO -   5 25873    5  1360    0     0    212      0  0:02:02  0:00:06  0:01:56   212
[2024-04-24T09:48:36.761+0000] {subprocess.py:93} INFO - curl: (23) Failure writing output to destination
[2024-04-24T09:48:36.762+0000] {subprocess.py:97} INFO - Command exited with return code 23
[2024-04-24T09:48:36.768+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 23.
[2024-04-24T09:48:36.769+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=download_rocket_launches, task_id=download_launches, execution_date=20240424T094829, start_date=20240424T094830, end_date=20240424T094836
[2024-04-24T09:48:36.777+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 18 for task download_launches (Bash command failed. The command returned a non-zero exit code 23.; 566)
[2024-04-24T09:48:36.808+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-24T09:48:36.820+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
